/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;
import dao.*;
import java.text.SimpleDateFormat;
import java.util.*;
import modelo.*;
/**
 *
 * @author Alan
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        setLocationRelativeTo( null );
        //popularBD();
        ClienteDAO clidao = new ClienteDAO();
        clientes = clidao.getListar();
        for(Cliente item: clientes)
        {   jComboBox1.addItem(item.getId()+ " - " + item.getNome());
        }
        
        //DATA
        Date sysdata = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jdate.setText(formato.format(sysdata));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCliente = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSaida = new javax.swing.JButton();
        lbData = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        jdate1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERAÇÃO DE CONTEUDO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("NOME DO CLIENTE");

        jLabel2.setText("DATA DA COMPRA");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnCliente.setText("GERENCIAR CLIENTE");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnProduto.setText("GERENCIAR PRODUTO");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnCompra.setText("GERENCIAR COMPRA");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnVenda.setText("VENDA");
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setText("RELATORIOS DE VENDAS");

        btnSaida.setText("SAIR");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        lbData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbHora.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdate.setText("12/12/2019");

        jdate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdate1.setText("Hoje é dia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(btnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(124, 124, 124))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbData)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbHora)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jdate1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jdate))
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(60, 60, 60))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(93, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(lbHora))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdate)
                    .addComponent(jdate1))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 977, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int apertei = jComboBox1.getSelectedIndex();
        if(apertei >= 0)
        {   int id = clientes.get(apertei).getId();
            CompraDAO cmpdao = new CompraDAO();
            compras = cmpdao.getListar(id);
            jComboBox2.removeAllItems();
            jTextArea1.setText("---Sem dados---");
            for(Compra item: compras)
            {   jComboBox2.addItem(item.getCodigo() + " - " + item.getData() + " - " + item.getValor());
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        int apertei = jComboBox2.getSelectedIndex();
        if(apertei >= 0)
        {   int id = compras.get(apertei).getCodigo();
            ItensCompradosDAO itensdao = new ItensCompradosDAO();
            itensdao.lerItens(compras.get(apertei)); //lendo os itens comprados
            jTextArea1.setText(compras.get(apertei).toString());
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
         ConsultarCliente obj = new ConsultarCliente();
         obj.setVisible(true);
         CRUD.this.dispose();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        ConsultarProduto obj = new ConsultarProduto();
        obj.setVisible(true);
        CRUD.this.dispose();
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        ConsultarCompra obj = new ConsultarCompra();
        obj.setVisible(true);
        CRUD.this.dispose();
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        ConsultarItens obj = new ConsultarItens();
        obj.setVisible(true);
        CRUD.this.dispose();
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnVenda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jdate1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables
    private List<Cliente> clientes;
    private List<Compra> compras;

    private void popularBD()
    {
        //Clientes
        ContatoDAO cdao = new ContatoDAO();
        cdao.adiciona(new Contato("Celso", "c@gmail.com", "Rua XYZ, 123", "01/01/2000"));
        cdao.adiciona(new Contato("Aline", "a@gmail.com", "Rua XYZ, 234", "01/01/2002"));
        cdao.adiciona(new Contato("Alexandre", "ale@gmail.com", "Rua XYZ, 678", "01/01/2001")); // O Alexandre será somente contato 
        
        ClienteDAO clidao = new ClienteDAO();
        clidao.adiciona(new Cliente("Celso", "c@gmail.com", "Rua XYZ, 123", "01/01/2000", "123456789"));
        clidao.adiciona(new Cliente("Aline", "a@gmail.com", "Rua XYZ, 234", "01/01/2002", "234567890"));
        clidao.adiciona(new Cliente("Marcelo", "m@gmail.com", "Rua ABC, 234", "01/01/1982", "3456789012")); //O Marcelo não era contato e foi adicionado direto como cliente
        
        //Estoque
        int id;
        ProdutoDAO pdao = new ProdutoDAO();
        Produto p1 = new Produto("Arroz Camil", 5.45f, 1000.0f);
        id = pdao.adiciona(p1);
        p1.setCodigo(id);
        Produto p2 = new Produto("Feijão Camil", 4.57f, 500.0f);
        id = pdao.adiciona(p2);
        p2.setCodigo(id);
        Produto p3 = new Produto("Carne Alcatra", 28.57f, 90.0f);
        id = pdao.adiciona(p3);
        p3.setCodigo(id);
        Produto p4 = new Produto("Salmão", 45.00f, 98.0f);
        id = pdao.adiciona(p4);
        p4.setCodigo(id);
        
        //Compra 1 da Aline (id=2)
        Compra compra1 = new Compra();
        compra1.setData("31/10/2019");
        ArrayList<Produto> itensCompradosAline1 = new ArrayList<Produto>();
        ArrayList<Float> quantCompradaAline1 = new ArrayList<Float>();
        itensCompradosAline1.add(p1); //Arroz Camil
        quantCompradaAline1.add(2f); //2 kg
        itensCompradosAline1.add(p2); //Feijão Camil
        quantCompradaAline1.add(1f); //1 kg
        itensCompradosAline1.add(p4); //Salmao Chileno
        quantCompradaAline1.add(2f); //2 kg
        compra1.setItensComprados(itensCompradosAline1);
        compra1.setQuantidades(quantCompradaAline1);
        compra1.setValor(2*5.45f + 1*4.57f + 2*45.00f);
        //armazenando a compra (sem os itens ainda)
        CompraDAO compradao = new CompraDAO();
        id = compradao.adiciona(compra1, 2); //id da Aline é 2
        compra1.setCodigo(id);
        //armazenando os itens comprados
        ItensCompradosDAO itensdao = new ItensCompradosDAO();
        itensdao.gravaItens(compra1);
       
        
        //Compra 2 da Aline (id=2)
        Compra compra2 = new Compra();
        compra2.setData("29/11/2019");
        ArrayList<Produto> itensCompradosAline2 = new ArrayList<Produto>();
        ArrayList<Float> quantCompradaAline2 = new ArrayList<Float>();
        itensCompradosAline2.add(p3); //Carne Alcatra
        quantCompradaAline2.add(1f); //1 kg
        itensCompradosAline2.add(p2); //Feijão Camil
        quantCompradaAline2.add(2f); //2 kg
        compra2.setItensComprados(itensCompradosAline2);
        compra2.setQuantidades(quantCompradaAline2);
        compra2.setValor(28.57f + 2*4.57f);
        //armazenando a compra (sem os itens ainda)
        id = compradao.adiciona(compra2, 2); //id da Aline é 2
        compra2.setCodigo(id);
        //armazenando os itens comprados
        itensdao.gravaItens(compra2);
        
        //Compra do Celso (id=1)
        Compra compra3 = new Compra();
        compra3.setData("03/11/2019");
        ArrayList<Produto> itensCompradosCelso = new ArrayList<Produto>();
        ArrayList<Float> quantCompradaCelso = new ArrayList<Float>();
        itensCompradosCelso.add(p1); //Arroz Camil
        quantCompradaCelso.add(3f); //3 kg
        compra3.setItensComprados(itensCompradosCelso);
        compra3.setQuantidades(quantCompradaCelso);
        compra3.setValor(3*5.45f);
        //armazenando a compra (sem os itens ainda)
        compradao = new CompraDAO();
        id = compradao.adiciona(compra3, 1); //id do Celso é 1
        compra3.setCodigo(id);
        //armazenando os itens comprados
        itensdao.gravaItens(compra3);
        
        //Compra do Marcelo (id=4)
        Compra compra4 = new Compra();
        compra4.setData("04/11/2019");
        ArrayList<Produto> itensCompradosMarcelo = new ArrayList<Produto>();
        ArrayList<Float> quantCompradaMarcelo = new ArrayList<Float>();
        itensCompradosMarcelo.add(p2); //Feijão Camil
        quantCompradaMarcelo.add(1f); //1 kg
        compra4.setItensComprados(itensCompradosMarcelo);
        compra4.setQuantidades(quantCompradaMarcelo);
        compra4.setValor(1*4.57f);
        //armazenando a compra (sem os itens ainda)
        compradao = new CompraDAO();
        id = compradao.adiciona(compra4, 4); //id do Marcelo é 4
        compra4.setCodigo(id);
        //armazenando os itens comprados
        itensdao.gravaItens(compra4);
    }
}
